name: test3

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Generate Containerfile
        run: curl -s https://raw.githubusercontent.com/emblem-66/test3/refs/heads/main/generate-containerfile.sh | bash
      - name: Build image
        run: podman build -t my-fedora-image -f Containerfile .
